In [1]:
# The basic CNN structure is as follows:
# Convolution -> Pooling -> Convolution -> Pooling
# -> Fully Connected Layer -> Output

# Setting up...
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard
import pickle
import time

NAME = "Finding-Pneumonia-Chest-X-rays-{}".format(int(time.time()))

tensorboard = TensorBoard(log_dir='logs/{}'.format(NAME))

X = pickle.load(open("X.pickle", "rb"))
y = pickle.load(open("y.pickle", "rb"))

X = np.array(X/255.0)
y = np.array(y)
y = tf.keras.utils.to_categorical(y, 3)

print(y)

model = Sequential()
# Convolution -> Pooling (1st)
model.add(Conv2D(16, (3,3), input_shape = X.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

# Convolution -> Pooling (2nd)
model.add(Conv2D(32, (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

# Convolution -> Pooling (3rd)
model.add(Conv2D(64, (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

# Convolution -> Pooling (4th)
model.add(Conv2D(64, (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

# Convolution -> Pooling (5th)
model.add(Conv2D(64, (3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

# Fully Connected Layer
model.add(Flatten())
model.add(Dense(512))
model.add(Activation("relu"))

# Output
model.add(Dense(3))
model.add(Activation("softmax"))

model.compile(loss = "categorical_crossentropy",
             optimizer = "adam",
             metrics=['accuracy'])

model.fit(X, y, batch_size=128, epochs=10, validation_split=0.3, callbacks = [tensorboard])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Epoch 1/10
 1/22 [>.............................] - ETA: 0s - loss: 1.1041 - accuracy: 0.2891WARNING:tensorflow:From C:\Users\user\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
22/22 [==============================] - 42s 2s/step - loss: 1.0308 - accuracy: 0.4375 - val_loss: 0.8533 - val_accuracy: 0.6404
Epoch 2/10
22/22 [==============================] - 43s 2s/step - loss: 0.6499 - accuracy: 0.7376 - val_loss: 0.5255 - val_accuracy: 0.7862
Epoch 3/10
22/22 [==============================] - 43s 2s/step - loss: 0.4652 - accuracy: 0.8068 - val_loss: 0.4234 - val_accuracy: 0.8285
Epoch 4/10
22/22 [==============================] - 43s 2s/step - loss: 0.3927 - accuracy: 0.8501 - val_loss: 0.4146 - val_accu

In [2]:
model.save("X-ray-CNN.model")

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: X-ray-CNN.model\assets
